# Generated by Django 2.0.6 on 2018-06-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modelcompletion', '0002_auto_20150712_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='IonChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('completion', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('completion', models.IntegerField(default=170)),
            ],
        ),
        migrations.CreateModel(
            name='Neuron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('completion', models.IntegerField(default=170)),
            ],
        ),
    ]
